language: node_js
node_js:
  - '7'
  - '6'
  - '4'

before_install:
  - npm install -g codecov

script:
  - npm prune
  - npm update
  - npm run prepublish
  - codecov

cache:
  directories:
    - node_modules

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
