language: node_js
node_js:
  - '7'
  - '6'
  - '4'

before_install:
  - npm install -g codecov

script:
  - npm prune
  - npm update
  - npm run prepublish

cache:
  directories:
    - node_modules

after_success:
  - codecov
